/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class IF22ScopeProvider extends AbstractIF22ScopeProvider {
}
