/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.mmmi.mdsd.ide.contentassist.antlr.internal.InternalMathParser;
import dk.sdu.mmmi.mdsd.services.MathGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MathParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MathGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MathGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getExpAccess().getAlternatives_1_0(), "rule__Exp__Alternatives_1_0");
			builder.put(grammarAccess.getMultDivAccess().getAlternatives_1_0(), "rule__MultDiv__Alternatives_1_0");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
			builder.put(grammarAccess.getProgramNameAccess().getGroup(), "rule__ProgramName__Group__0");
			builder.put(grammarAccess.getExternalAccess().getGroup(), "rule__External__Group__0");
			builder.put(grammarAccess.getExternalAccess().getGroup_5(), "rule__External__Group_5__0");
			builder.put(grammarAccess.getExternalUseAccess().getGroup(), "rule__ExternalUse__Group__0");
			builder.put(grammarAccess.getExternalUseAccess().getGroup_4(), "rule__ExternalUse__Group_4__0");
			builder.put(grammarAccess.getVariableAssignmentAccess().getGroup(), "rule__VariableAssignment__Group__0");
			builder.put(grammarAccess.getExpAccess().getGroup(), "rule__Exp__Group__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1(), "rule__Exp__Group_1__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1_0_0(), "rule__Exp__Group_1_0_0__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1_0_1(), "rule__Exp__Group_1_0_1__0");
			builder.put(grammarAccess.getMultDivAccess().getGroup(), "rule__MultDiv__Group__0");
			builder.put(grammarAccess.getMultDivAccess().getGroup_1(), "rule__MultDiv__Group_1__0");
			builder.put(grammarAccess.getMultDivAccess().getGroup_1_0_0(), "rule__MultDiv__Group_1_0_0__0");
			builder.put(grammarAccess.getMultDivAccess().getGroup_1_0_1(), "rule__MultDiv__Group_1_0_1__0");
			builder.put(grammarAccess.getParenthesisAccess().getGroup(), "rule__Parenthesis__Group__0");
			builder.put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
			builder.put(grammarAccess.getVariableUseAccess().getGroup(), "rule__VariableUse__Group__0");
			builder.put(grammarAccess.getAssignmentAccess().getGroup(), "rule__Assignment__Group__0");
			builder.put(grammarAccess.getLocalAssignmentAccess().getGroup(), "rule__LocalAssignment__Group__0");
			builder.put(grammarAccess.getProgramAccess().getProgramNameAssignment_0(), "rule__Program__ProgramNameAssignment_0");
			builder.put(grammarAccess.getProgramAccess().getExternalsAssignment_1(), "rule__Program__ExternalsAssignment_1");
			builder.put(grammarAccess.getProgramAccess().getVariableAssignmentsAssignment_2(), "rule__Program__VariableAssignmentsAssignment_2");
			builder.put(grammarAccess.getProgramNameAccess().getNameAssignment_1(), "rule__ProgramName__NameAssignment_1");
			builder.put(grammarAccess.getExternalAccess().getNameAssignment_2(), "rule__External__NameAssignment_2");
			builder.put(grammarAccess.getExternalAccess().getParametersAssignment_4(), "rule__External__ParametersAssignment_4");
			builder.put(grammarAccess.getExternalAccess().getParametersAssignment_5_1(), "rule__External__ParametersAssignment_5_1");
			builder.put(grammarAccess.getExternalUseAccess().getRefAssignment_1(), "rule__ExternalUse__RefAssignment_1");
			builder.put(grammarAccess.getExternalUseAccess().getExpAssignment_3(), "rule__ExternalUse__ExpAssignment_3");
			builder.put(grammarAccess.getExternalUseAccess().getExpAssignment_4_1(), "rule__ExternalUse__ExpAssignment_4_1");
			builder.put(grammarAccess.getVariableAssignmentAccess().getNameAssignment_2(), "rule__VariableAssignment__NameAssignment_2");
			builder.put(grammarAccess.getVariableAssignmentAccess().getExpAssignment_4(), "rule__VariableAssignment__ExpAssignment_4");
			builder.put(grammarAccess.getExpAccess().getRightAssignment_1_1(), "rule__Exp__RightAssignment_1_1");
			builder.put(grammarAccess.getMultDivAccess().getRightAssignment_1_1(), "rule__MultDiv__RightAssignment_1_1");
			builder.put(grammarAccess.getParenthesisAccess().getExpAssignment_2(), "rule__Parenthesis__ExpAssignment_2");
			builder.put(grammarAccess.getNumberAccess().getValueAssignment_1(), "rule__Number__ValueAssignment_1");
			builder.put(grammarAccess.getVariableUseAccess().getRefAssignment_1(), "rule__VariableUse__RefAssignment_1");
			builder.put(grammarAccess.getAssignmentAccess().getNameAssignment_1(), "rule__Assignment__NameAssignment_1");
			builder.put(grammarAccess.getAssignmentAccess().getExpAssignment_3(), "rule__Assignment__ExpAssignment_3");
			builder.put(grammarAccess.getLocalAssignmentAccess().getAssignmentAssignment_2(), "rule__LocalAssignment__AssignmentAssignment_2");
			builder.put(grammarAccess.getLocalAssignmentAccess().getExpAssignment_4(), "rule__LocalAssignment__ExpAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MathGrammarAccess grammarAccess;

	@Override
	protected InternalMathParser createParser() {
		InternalMathParser result = new InternalMathParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MathGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
