/* 
 * Generated by xtend by the generator made by 'Frederik Alexander Hounsvad' 'frhou18@student.sdu.dk'
 * All Rights reserved
*/
package math_expression;
public class Test21{
	public int x;
	public int y;
	
	
	public void compute(){
		x = ((42));
		y = ((((42))));
	}
	
}
