/* 
 * Generated by xtend by the generator made by 'Frederik Alexander Hounsvad' 'frhou18@student.sdu.dk'
 * All Rights reserved
*/
package math_expression;
public class Test28{
	public int x;
	public int y;
	
	private External external;
	
	public Test28(External external){
		this.external = external;
	}
		
	public interface External{
		public int sqrt(int n);
	}
	
	public void compute(){
		x = ((external.sqrt((4))));
		y = (((((external.sqrt((4))))) * (2)));
	}
	
}
