/* 
 * Generated by xtend by the generator made by 'Frederik Alexander Hounsvad' 'frhou18@student.sdu.dk'
 * All Rights reserved
*/
package math_expression;
public class Test30{
	public int x;
	
	private External external;
	
	public Test30(External external){
		this.external = external;
	}
		
	public interface External{
		public int pow(int n, int m);
		public int sqrt(int n);
		public int pi();
	}
	
	public void compute(){
		x = ((external.sqrt((external.pow((external.pi()),(2))))));
	}
	
}
