/* 
 * Generated by xtend by the generator made by 'Frederik Alexander Hounsvad' 'frhou18@student.sdu.dk'
 * All Rights reserved
*/
package math_expression;
public class Test24{
	public int x;
	public int y;
	
	
	public void compute(){
		x = ((21));
		y = ((((((((21))))) * (2))));
	}
	
}
