/* 
 * Generated by xtend by the generator made by 'Frederik Alexander Hounsvad' 'frhou18@student.sdu.dk'
 * All Rights reserved
*/
package math_expression;
public class Test20{
	public int x;
	
	
	public void compute(){
		x = (((((((((3))) * (((3))))) + (((2))))) + (76)));
	}
	
}
