/* 
 * Generated by xtend by the generator made by 'Frederik Alexander Hounsvad' 'frhou18@student.sdu.dk'
 * All Rights reserved
*/
package math_expression;
public class Test16{
	public int x;
	
	
	public void compute(){
		x = (((((10) + ((3) * (4))) - ((12) / (3))) + (3)));
	}
	
}
