/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.impl;

import dk.sdu.mmmi.mdsd.math.LocalAssignment;
import dk.sdu.mmmi.mdsd.math.MathPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Local Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LocalAssignmentImpl extends ExpressionImpl implements LocalAssignment
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LocalAssignmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathPackage.Literals.LOCAL_ASSIGNMENT;
  }

} //LocalAssignmentImpl
