/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IF22AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dk/sdu/frhou18/mdsd/parser/antlr/internal/InternalIF22.tokens");
	}
}
