/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.ui;

import com.google.inject.Injector;
import dk.sdu.frhou18.mdsd.ui.internal.MdsdActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IF22ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MdsdActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MdsdActivator activator = MdsdActivator.getInstance();
		return activator != null ? activator.getInjector(MdsdActivator.DK_SDU_FRHOU18_MDSD_IF22) : null;
	}

}
