/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.frhou18.mdsd.ui.internal.MdsdActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IF22UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdsdActivator.getInstance().getInjector("dk.sdu.frhou18.mdsd.IF22");
	}

}
