/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getExpression()
 * @model
 * @generated
 */
public interface Expression extends StringProducer
{
} // Expression
