/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.Model#getStoryName <em>Story Name</em>}</li>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.Model#getFunctions <em>Functions</em>}</li>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.Model#getScenarios <em>Scenarios</em>}</li>
 * </ul>
 *
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Story Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Story Name</em>' containment reference.
   * @see #setStoryName(Story)
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getModel_StoryName()
   * @model containment="true"
   * @generated
   */
  Story getStoryName();

  /**
   * Sets the value of the '{@link dk.sdu.frhou18.mdsd.iF22.Model#getStoryName <em>Story Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Story Name</em>' containment reference.
   * @see #getStoryName()
   * @generated
   */
  void setStoryName(Story value);

  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.frhou18.mdsd.iF22.Function}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getModel_Functions()
   * @model containment="true"
   * @generated
   */
  EList<Function> getFunctions();

  /**
   * Returns the value of the '<em><b>Scenarios</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.frhou18.mdsd.iF22.Scenario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenarios</em>' containment reference list.
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getModel_Scenarios()
   * @model containment="true"
   * @generated
   */
  EList<Scenario> getScenarios();

} // Model
