/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getStatement()
 * @model
 * @generated
 */
public interface Statement extends TargetTarget
{
} // Statement
