/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.Boolean#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends Expression
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * The literals are from the enumeration {@link dk.sdu.frhou18.mdsd.iF22.BooleanValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see dk.sdu.frhou18.mdsd.iF22.BooleanValue
   * @see #setVal(BooleanValue)
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getBoolean_Val()
   * @model
   * @generated
   */
  BooleanValue getVal();

  /**
   * Sets the value of the '{@link dk.sdu.frhou18.mdsd.iF22.Boolean#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see dk.sdu.frhou18.mdsd.iF22.BooleanValue
   * @see #getVal()
   * @generated
   */
  void setVal(BooleanValue value);

} // Boolean
