/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Usage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.FunctionUsage#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.FunctionUsage#getExps <em>Exps</em>}</li>
 * </ul>
 *
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getFunctionUsage()
 * @model
 * @generated
 */
public interface FunctionUsage extends Expression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Function)
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getFunctionUsage_Name()
   * @model
   * @generated
   */
  Function getName();

  /**
   * Sets the value of the '{@link dk.sdu.frhou18.mdsd.iF22.FunctionUsage#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Function value);

  /**
   * Returns the value of the '<em><b>Exps</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.frhou18.mdsd.iF22.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exps</em>' containment reference list.
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getFunctionUsage_Exps()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExps();

} // FunctionUsage
