/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Factory
 * @model kind="package"
 * @generated
 */
public interface IF22Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iF22";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sdu.dk/frhou18/mdsd/IF22";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iF22";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IF22Package eINSTANCE = dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl.init();

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.ModelImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Story Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STORY_NAME = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FUNCTIONS = 1;

  /**
   * The feature id for the '<em><b>Scenarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SCENARIOS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.FunctionImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__TYPE = 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.StoryImpl <em>Story</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.StoryImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getStory()
   * @generated
   */
  int STORY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY__NAME = 0;

  /**
   * The number of structural features of the '<em>Story</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TargetTargetImpl <em>Target Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.TargetTargetImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTargetTarget()
   * @generated
   */
  int TARGET_TARGET = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_TARGET__NAME = 0;

  /**
   * The number of structural features of the '<em>Target Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_TARGET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.ScenarioImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__NAME = TARGET_TARGET__NAME;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__VARIABLES = TARGET_TARGET_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Statemens</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__STATEMENS = TARGET_TARGET_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = TARGET_TARGET_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.StatementImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__NAME = TARGET_TARGET__NAME;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = TARGET_TARGET_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.EndImpl <em>End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.EndImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getEnd()
   * @generated
   */
  int END = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>End Message</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END__END_MESSAGE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.AnnounceImpl <em>Announce</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.AnnounceImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getAnnounce()
   * @generated
   */
  int ANNOUNCE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__TEXT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE__TARGET = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Announce</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOUNCE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.QuestionImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__NAME = STATEMENT__NAME;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__TEXT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>As Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__AS_VALUE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>In Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__IN_VAR = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Targets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__TARGETS = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.VariableDefImpl <em>Variable Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.VariableDefImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getVariableDef()
   * @generated
   */
  int VARIABLE_DEF = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEF__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEF__TYPE = 1;

  /**
   * The number of structural features of the '<em>Variable Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TargetImpl <em>Target</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.TargetImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTarget()
   * @generated
   */
  int TARGET = 9;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__TARGET = 0;

  /**
   * The feature id for the '<em><b>Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET__LOGIC = 1;

  /**
   * The number of structural features of the '<em>Target</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TARGET_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.StringProducerImpl <em>String Producer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.StringProducerImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getStringProducer()
   * @generated
   */
  int STRING_PRODUCER = 11;

  /**
   * The number of structural features of the '<em>String Producer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PRODUCER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.ExpressionImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 12;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = STRING_PRODUCER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ThisImpl <em>This</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.ThisImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getThis()
   * @generated
   */
  int THIS = 13;

  /**
   * The number of structural features of the '<em>This</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THIS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.EqualsImpl <em>Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.EqualsImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getEquals()
   * @generated
   */
  int EQUALS = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.NotEqualsImpl <em>Not Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.NotEqualsImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getNotEquals()
   * @generated
   */
  int NOT_EQUALS = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EQUALS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EQUALS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Not Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EQUALS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.LessImpl <em>Less</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.LessImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getLess()
   * @generated
   */
  int LESS = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Less</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.GreaterImpl <em>Greater</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.GreaterImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getGreater()
   * @generated
   */
  int GREATER = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Greater</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.LessOrEqualsImpl <em>Less Or Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.LessOrEqualsImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getLessOrEquals()
   * @generated
   */
  int LESS_OR_EQUALS = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUALS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUALS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Less Or Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_OR_EQUALS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.GreaterOrEqualsImpl <em>Greater Or Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.GreaterOrEqualsImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getGreaterOrEquals()
   * @generated
   */
  int GREATER_OR_EQUALS = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_OR_EQUALS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_OR_EQUALS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Greater Or Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_OR_EQUALS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.AndImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getAnd()
   * @generated
   */
  int AND = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.OrImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getOr()
   * @generated
   */
  int OR = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.LogicNotImpl <em>Logic Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.LogicNotImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getLogicNot()
   * @generated
   */
  int LOGIC_NOT = 22;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_NOT__REF = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Logic Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_NOT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ParenthesesImpl <em>Parentheses</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.ParenthesesImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getParentheses()
   * @generated
   */
  int PARENTHESES = 23;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESES__REF = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parentheses</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESES_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.BooleanImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 24;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.PlusImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getPlus()
   * @generated
   */
  int PLUS = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.MinusImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getMinus()
   * @generated
   */
  int MINUS = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.MultiplicationImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.DivisionImpl <em>Division</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.DivisionImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getDivision()
   * @generated
   */
  int DIVISION = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVISION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVISION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Division</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVISION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.MathNumberExpImpl <em>Math Number Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.MathNumberExpImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getMathNumberExp()
   * @generated
   */
  int MATH_NUMBER_EXP = 29;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_NUMBER_EXP__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Math Number Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_NUMBER_EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TextExpImpl <em>Text Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.TextExpImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTextExp()
   * @generated
   */
  int TEXT_EXP = 30;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_EXP__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_EXP__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Text Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.FunctionUsageImpl <em>Function Usage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.FunctionUsageImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getFunctionUsage()
   * @generated
   */
  int FUNCTION_USAGE = 31;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_USAGE__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_USAGE__EXPS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function Usage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_USAGE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TextLiteralImpl <em>Text Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.TextLiteralImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTextLiteral()
   * @generated
   */
  int TEXT_LITERAL = 32;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_LITERAL__TEXT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.VarUseImpl <em>Var Use</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.VarUseImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getVarUse()
   * @generated
   */
  int VAR_USE = 33;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_USE__REF = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Use</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_USE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TypeUsageImpl <em>Type Usage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.impl.TypeUsageImpl
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTypeUsage()
   * @generated
   */
  int TYPE_USAGE = 34;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_USAGE__TYPE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type Usage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_USAGE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.Type <em>Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.Type
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getType()
   * @generated
   */
  int TYPE = 35;

  /**
   * The meta object id for the '{@link dk.sdu.frhou18.mdsd.iF22.BooleanValue <em>Boolean Value</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.frhou18.mdsd.iF22.BooleanValue
   * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getBooleanValue()
   * @generated
   */
  int BOOLEAN_VALUE = 36;


  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Model#getStoryName <em>Story Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Story Name</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Model#getStoryName()
   * @see #getModel()
   * @generated
   */
  EReference getModel_StoryName();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.frhou18.mdsd.iF22.Model#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Model#getFunctions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Functions();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.frhou18.mdsd.iF22.Model#getScenarios <em>Scenarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenarios</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Model#getScenarios()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Scenarios();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.frhou18.mdsd.iF22.Function#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Function#getParameters()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Parameters();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.Function#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Function#getType()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Type();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Story <em>Story</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Story</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Story
   * @generated
   */
  EClass getStory();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.Story#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Story#getName()
   * @see #getStory()
   * @generated
   */
  EAttribute getStory_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.frhou18.mdsd.iF22.Scenario#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Scenario#getVariables()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.frhou18.mdsd.iF22.Scenario#getStatemens <em>Statemens</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statemens</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Scenario#getStatemens()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Statemens();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.End <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.End
   * @generated
   */
  EClass getEnd();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.End#getEndMessage <em>End Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>End Message</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.End#getEndMessage()
   * @see #getEnd()
   * @generated
   */
  EReference getEnd_EndMessage();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Announce <em>Announce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Announce</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Announce
   * @generated
   */
  EClass getAnnounce();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Announce#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Announce#getText()
   * @see #getAnnounce()
   * @generated
   */
  EReference getAnnounce_Text();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Announce#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Target</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Announce#getTarget()
   * @see #getAnnounce()
   * @generated
   */
  EReference getAnnounce_Target();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Question#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Question#getText()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Text();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Question#getAsValue <em>As Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>As Value</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Question#getAsValue()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_AsValue();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Question#getInVar <em>In Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>In Var</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Question#getInVar()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_InVar();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.frhou18.mdsd.iF22.Question#getTargets <em>Targets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Targets</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Question#getTargets()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Targets();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.VariableDef <em>Variable Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Def</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.VariableDef
   * @generated
   */
  EClass getVariableDef();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.VariableDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.VariableDef#getName()
   * @see #getVariableDef()
   * @generated
   */
  EAttribute getVariableDef_Name();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.VariableDef#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.VariableDef#getType()
   * @see #getVariableDef()
   * @generated
   */
  EAttribute getVariableDef_Type();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Target <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Target
   * @generated
   */
  EClass getTarget();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.frhou18.mdsd.iF22.Target#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Target#getTarget()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Target();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Target#getLogic <em>Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Logic</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Target#getLogic()
   * @see #getTarget()
   * @generated
   */
  EReference getTarget_Logic();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.TargetTarget <em>Target Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Target Target</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TargetTarget
   * @generated
   */
  EClass getTargetTarget();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.TargetTarget#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TargetTarget#getName()
   * @see #getTargetTarget()
   * @generated
   */
  EAttribute getTargetTarget_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.StringProducer <em>String Producer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Producer</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.StringProducer
   * @generated
   */
  EClass getStringProducer();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.This <em>This</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>This</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.This
   * @generated
   */
  EClass getThis();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Equals <em>Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equals</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Equals
   * @generated
   */
  EClass getEquals();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Equals#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Equals#getLeft()
   * @see #getEquals()
   * @generated
   */
  EReference getEquals_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Equals#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Equals#getRight()
   * @see #getEquals()
   * @generated
   */
  EReference getEquals_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.NotEquals <em>Not Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Equals</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.NotEquals
   * @generated
   */
  EClass getNotEquals();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.NotEquals#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.NotEquals#getLeft()
   * @see #getNotEquals()
   * @generated
   */
  EReference getNotEquals_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.NotEquals#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.NotEquals#getRight()
   * @see #getNotEquals()
   * @generated
   */
  EReference getNotEquals_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Less <em>Less</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Less
   * @generated
   */
  EClass getLess();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Less#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Less#getLeft()
   * @see #getLess()
   * @generated
   */
  EReference getLess_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Less#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Less#getRight()
   * @see #getLess()
   * @generated
   */
  EReference getLess_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Greater <em>Greater</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greater</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Greater
   * @generated
   */
  EClass getGreater();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Greater#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Greater#getLeft()
   * @see #getGreater()
   * @generated
   */
  EReference getGreater_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Greater#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Greater#getRight()
   * @see #getGreater()
   * @generated
   */
  EReference getGreater_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.LessOrEquals <em>Less Or Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less Or Equals</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.LessOrEquals
   * @generated
   */
  EClass getLessOrEquals();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.LessOrEquals#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.LessOrEquals#getLeft()
   * @see #getLessOrEquals()
   * @generated
   */
  EReference getLessOrEquals_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.LessOrEquals#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.LessOrEquals#getRight()
   * @see #getLessOrEquals()
   * @generated
   */
  EReference getLessOrEquals_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.GreaterOrEquals <em>Greater Or Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greater Or Equals</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.GreaterOrEquals
   * @generated
   */
  EClass getGreaterOrEquals();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.GreaterOrEquals#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.GreaterOrEquals#getLeft()
   * @see #getGreaterOrEquals()
   * @generated
   */
  EReference getGreaterOrEquals_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.GreaterOrEquals#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.GreaterOrEquals#getRight()
   * @see #getGreaterOrEquals()
   * @generated
   */
  EReference getGreaterOrEquals_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.LogicNot <em>Logic Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Not</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.LogicNot
   * @generated
   */
  EClass getLogicNot();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.LogicNot#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.LogicNot#getRef()
   * @see #getLogicNot()
   * @generated
   */
  EReference getLogicNot_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Parentheses <em>Parentheses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parentheses</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Parentheses
   * @generated
   */
  EClass getParentheses();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Parentheses#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Parentheses#getRef()
   * @see #getParentheses()
   * @generated
   */
  EReference getParentheses_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.Boolean#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Boolean#getVal()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_Val();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.Division <em>Division</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Division</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Division
   * @generated
   */
  EClass getDivision();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Division#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Division#getLeft()
   * @see #getDivision()
   * @generated
   */
  EReference getDivision_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.Division#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Division#getRight()
   * @see #getDivision()
   * @generated
   */
  EReference getDivision_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.MathNumberExp <em>Math Number Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Math Number Exp</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.MathNumberExp
   * @generated
   */
  EClass getMathNumberExp();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.MathNumberExp#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.MathNumberExp#getValue()
   * @see #getMathNumberExp()
   * @generated
   */
  EAttribute getMathNumberExp_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.TextExp <em>Text Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Exp</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TextExp
   * @generated
   */
  EClass getTextExp();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.TextExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TextExp#getLeft()
   * @see #getTextExp()
   * @generated
   */
  EReference getTextExp_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.frhou18.mdsd.iF22.TextExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TextExp#getRight()
   * @see #getTextExp()
   * @generated
   */
  EReference getTextExp_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.FunctionUsage <em>Function Usage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Usage</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.FunctionUsage
   * @generated
   */
  EClass getFunctionUsage();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.frhou18.mdsd.iF22.FunctionUsage#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.FunctionUsage#getName()
   * @see #getFunctionUsage()
   * @generated
   */
  EReference getFunctionUsage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.frhou18.mdsd.iF22.FunctionUsage#getExps <em>Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exps</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.FunctionUsage#getExps()
   * @see #getFunctionUsage()
   * @generated
   */
  EReference getFunctionUsage_Exps();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.TextLiteral <em>Text Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Literal</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TextLiteral
   * @generated
   */
  EClass getTextLiteral();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.TextLiteral#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TextLiteral#getText()
   * @see #getTextLiteral()
   * @generated
   */
  EAttribute getTextLiteral_Text();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.VarUse <em>Var Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Use</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.VarUse
   * @generated
   */
  EClass getVarUse();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.frhou18.mdsd.iF22.VarUse#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.VarUse#getRef()
   * @see #getVarUse()
   * @generated
   */
  EReference getVarUse_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.frhou18.mdsd.iF22.TypeUsage <em>Type Usage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Usage</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TypeUsage
   * @generated
   */
  EClass getTypeUsage();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.frhou18.mdsd.iF22.TypeUsage#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.TypeUsage#getType()
   * @see #getTypeUsage()
   * @generated
   */
  EAttribute getTypeUsage_Type();

  /**
   * Returns the meta object for enum '{@link dk.sdu.frhou18.mdsd.iF22.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.Type
   * @generated
   */
  EEnum getType();

  /**
   * Returns the meta object for enum '{@link dk.sdu.frhou18.mdsd.iF22.BooleanValue <em>Boolean Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Boolean Value</em>'.
   * @see dk.sdu.frhou18.mdsd.iF22.BooleanValue
   * @generated
   */
  EEnum getBooleanValue();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IF22Factory getIF22Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.ModelImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Story Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STORY_NAME = eINSTANCE.getModel_StoryName();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FUNCTIONS = eINSTANCE.getModel_Functions();

    /**
     * The meta object literal for the '<em><b>Scenarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SCENARIOS = eINSTANCE.getModel_Scenarios();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.FunctionImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__PARAMETERS = eINSTANCE.getFunction_Parameters();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__TYPE = eINSTANCE.getFunction_Type();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.StoryImpl <em>Story</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.StoryImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getStory()
     * @generated
     */
    EClass STORY = eINSTANCE.getStory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORY__NAME = eINSTANCE.getStory_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.ScenarioImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__VARIABLES = eINSTANCE.getScenario_Variables();

    /**
     * The meta object literal for the '<em><b>Statemens</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__STATEMENS = eINSTANCE.getScenario_Statemens();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.StatementImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.EndImpl <em>End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.EndImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getEnd()
     * @generated
     */
    EClass END = eINSTANCE.getEnd();

    /**
     * The meta object literal for the '<em><b>End Message</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference END__END_MESSAGE = eINSTANCE.getEnd_EndMessage();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.AnnounceImpl <em>Announce</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.AnnounceImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getAnnounce()
     * @generated
     */
    EClass ANNOUNCE = eINSTANCE.getAnnounce();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOUNCE__TEXT = eINSTANCE.getAnnounce_Text();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANNOUNCE__TARGET = eINSTANCE.getAnnounce_Target();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.QuestionImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__TEXT = eINSTANCE.getQuestion_Text();

    /**
     * The meta object literal for the '<em><b>As Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__AS_VALUE = eINSTANCE.getQuestion_AsValue();

    /**
     * The meta object literal for the '<em><b>In Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__IN_VAR = eINSTANCE.getQuestion_InVar();

    /**
     * The meta object literal for the '<em><b>Targets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__TARGETS = eINSTANCE.getQuestion_Targets();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.VariableDefImpl <em>Variable Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.VariableDefImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getVariableDef()
     * @generated
     */
    EClass VARIABLE_DEF = eINSTANCE.getVariableDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DEF__NAME = eINSTANCE.getVariableDef_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DEF__TYPE = eINSTANCE.getVariableDef_Type();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TargetImpl <em>Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.TargetImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTarget()
     * @generated
     */
    EClass TARGET = eINSTANCE.getTarget();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__TARGET = eINSTANCE.getTarget_Target();

    /**
     * The meta object literal for the '<em><b>Logic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TARGET__LOGIC = eINSTANCE.getTarget_Logic();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TargetTargetImpl <em>Target Target</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.TargetTargetImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTargetTarget()
     * @generated
     */
    EClass TARGET_TARGET = eINSTANCE.getTargetTarget();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TARGET_TARGET__NAME = eINSTANCE.getTargetTarget_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.StringProducerImpl <em>String Producer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.StringProducerImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getStringProducer()
     * @generated
     */
    EClass STRING_PRODUCER = eINSTANCE.getStringProducer();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.ExpressionImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ThisImpl <em>This</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.ThisImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getThis()
     * @generated
     */
    EClass THIS = eINSTANCE.getThis();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.EqualsImpl <em>Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.EqualsImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getEquals()
     * @generated
     */
    EClass EQUALS = eINSTANCE.getEquals();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALS__LEFT = eINSTANCE.getEquals_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALS__RIGHT = eINSTANCE.getEquals_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.NotEqualsImpl <em>Not Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.NotEqualsImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getNotEquals()
     * @generated
     */
    EClass NOT_EQUALS = eINSTANCE.getNotEquals();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EQUALS__LEFT = eINSTANCE.getNotEquals_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EQUALS__RIGHT = eINSTANCE.getNotEquals_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.LessImpl <em>Less</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.LessImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getLess()
     * @generated
     */
    EClass LESS = eINSTANCE.getLess();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS__LEFT = eINSTANCE.getLess_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS__RIGHT = eINSTANCE.getLess_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.GreaterImpl <em>Greater</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.GreaterImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getGreater()
     * @generated
     */
    EClass GREATER = eINSTANCE.getGreater();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREATER__LEFT = eINSTANCE.getGreater_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREATER__RIGHT = eINSTANCE.getGreater_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.LessOrEqualsImpl <em>Less Or Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.LessOrEqualsImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getLessOrEquals()
     * @generated
     */
    EClass LESS_OR_EQUALS = eINSTANCE.getLessOrEquals();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS_OR_EQUALS__LEFT = eINSTANCE.getLessOrEquals_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LESS_OR_EQUALS__RIGHT = eINSTANCE.getLessOrEquals_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.GreaterOrEqualsImpl <em>Greater Or Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.GreaterOrEqualsImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getGreaterOrEquals()
     * @generated
     */
    EClass GREATER_OR_EQUALS = eINSTANCE.getGreaterOrEquals();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREATER_OR_EQUALS__LEFT = eINSTANCE.getGreaterOrEquals_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREATER_OR_EQUALS__RIGHT = eINSTANCE.getGreaterOrEquals_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.AndImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.OrImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.LogicNotImpl <em>Logic Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.LogicNotImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getLogicNot()
     * @generated
     */
    EClass LOGIC_NOT = eINSTANCE.getLogicNot();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_NOT__REF = eINSTANCE.getLogicNot_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.ParenthesesImpl <em>Parentheses</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.ParenthesesImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getParentheses()
     * @generated
     */
    EClass PARENTHESES = eINSTANCE.getParentheses();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTHESES__REF = eINSTANCE.getParentheses_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.BooleanImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__VAL = eINSTANCE.getBoolean_Val();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.PlusImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.MinusImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.MultiplicationImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.DivisionImpl <em>Division</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.DivisionImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getDivision()
     * @generated
     */
    EClass DIVISION = eINSTANCE.getDivision();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVISION__LEFT = eINSTANCE.getDivision_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVISION__RIGHT = eINSTANCE.getDivision_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.MathNumberExpImpl <em>Math Number Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.MathNumberExpImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getMathNumberExp()
     * @generated
     */
    EClass MATH_NUMBER_EXP = eINSTANCE.getMathNumberExp();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATH_NUMBER_EXP__VALUE = eINSTANCE.getMathNumberExp_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TextExpImpl <em>Text Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.TextExpImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTextExp()
     * @generated
     */
    EClass TEXT_EXP = eINSTANCE.getTextExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_EXP__LEFT = eINSTANCE.getTextExp_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_EXP__RIGHT = eINSTANCE.getTextExp_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.FunctionUsageImpl <em>Function Usage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.FunctionUsageImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getFunctionUsage()
     * @generated
     */
    EClass FUNCTION_USAGE = eINSTANCE.getFunctionUsage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_USAGE__NAME = eINSTANCE.getFunctionUsage_Name();

    /**
     * The meta object literal for the '<em><b>Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_USAGE__EXPS = eINSTANCE.getFunctionUsage_Exps();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TextLiteralImpl <em>Text Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.TextLiteralImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTextLiteral()
     * @generated
     */
    EClass TEXT_LITERAL = eINSTANCE.getTextLiteral();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_LITERAL__TEXT = eINSTANCE.getTextLiteral_Text();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.VarUseImpl <em>Var Use</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.VarUseImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getVarUse()
     * @generated
     */
    EClass VAR_USE = eINSTANCE.getVarUse();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_USE__REF = eINSTANCE.getVarUse_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.impl.TypeUsageImpl <em>Type Usage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.impl.TypeUsageImpl
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getTypeUsage()
     * @generated
     */
    EClass TYPE_USAGE = eINSTANCE.getTypeUsage();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_USAGE__TYPE = eINSTANCE.getTypeUsage_Type();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.Type <em>Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.Type
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getType()
     * @generated
     */
    EEnum TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link dk.sdu.frhou18.mdsd.iF22.BooleanValue <em>Boolean Value</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.frhou18.mdsd.iF22.BooleanValue
     * @see dk.sdu.frhou18.mdsd.iF22.impl.IF22PackageImpl#getBooleanValue()
     * @generated
     */
    EEnum BOOLEAN_VALUE = eINSTANCE.getBooleanValue();

  }

} //IF22Package
