/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Producer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getStringProducer()
 * @model
 * @generated
 */
public interface StringProducer extends EObject
{
} // StringProducer
