/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.iF22;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.Target#getTarget <em>Target</em>}</li>
 *   <li>{@link dk.sdu.frhou18.mdsd.iF22.Target#getLogic <em>Logic</em>}</li>
 * </ul>
 *
 * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getTarget()
 * @model
 * @generated
 */
public interface Target extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(TargetTarget)
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getTarget_Target()
   * @model
   * @generated
   */
  TargetTarget getTarget();

  /**
   * Sets the value of the '{@link dk.sdu.frhou18.mdsd.iF22.Target#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(TargetTarget value);

  /**
   * Returns the value of the '<em><b>Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic</em>' containment reference.
   * @see #setLogic(Expression)
   * @see dk.sdu.frhou18.mdsd.iF22.IF22Package#getTarget_Logic()
   * @model containment="true"
   * @generated
   */
  Expression getLogic();

  /**
   * Sets the value of the '{@link dk.sdu.frhou18.mdsd.iF22.Target#getLogic <em>Logic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logic</em>' containment reference.
   * @see #getLogic()
   * @generated
   */
  void setLogic(Expression value);

} // Target
