/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractIF22Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dk.sdu.frhou18.mdsd.iF22.IF22Package.eINSTANCE);
		return result;
	}
}
