/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.frhou18.mdsd.ide

import com.google.inject.Guice
import dk.sdu.frhou18.mdsd.IF22RuntimeModule
import dk.sdu.frhou18.mdsd.IF22StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IF22IdeSetup extends IF22StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IF22RuntimeModule, new IF22IdeModule))
	}
	
}
